modLoader="javafml"
loaderVersion="[45,)"
license="MPL-2.0"
issueTrackerURL="https://github.com/Tslat/TslatEntityStatus/issues"

[[mods]]
modId="tslatentitystatus"
version="1.1.2"
displayName="TES"
logoFile="logo.png"
authors="Tslat"
displayTest="IGNORE_SERVER_VERSION"
description='''
View entity health and other statuses. Make smacking things fun again!
'''

[[dependencies.tslatentitystatus]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.tslatentitystatus]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,)"
ordering="NONE"
side="BOTH"
